pushing it back to 1.42.9 for testing

diff --git a/lib/et/compile_et.sh.in b/lib/et/compile_et.sh.in
--- a/lib/et/compile_et.sh.in
+++ b/lib/et/compile_et.sh.in
@@ -2,8 +2,10 @@
 #
 #
 
+datarootdir=@datarootdir@
 AWK=@AWK@
-DIR=@datadir@/et
+DIR="${DIR-@datadir@/et}"
+ET_DIR="@ET_DIR@"
 
 if test "$1" = "--build-tree" ; then
     shift;
@@ -27,13 +29,13 @@ do
   fi
 done
 
-if test -n "$_ET_DIR_OVERRIDE" ; then
-    DIR="$_ET_DIR_OVERRIDE";
-fi
-
 if test ! -f "$DIR/et_h.awk" || test ! -f "$DIR/et_c.awk" ; then
-    echo "compile_et: Couldn't find compile_et's template files."
-    exit 1
+    DIR="$ET_DIR"
+#    echo "Falling back to $DIR..."
+    if test ! -f "$DIR/et_h.awk" || test ! -f "$DIR/et_c.awk" ; then
+	echo "compile_et: Couldn't find compile_et's template files."
+	exit 1
+    fi
 fi
 
 ROOT=`echo $1 | sed -e s/.et$//`
@@ -49,12 +51,12 @@ if test -f ${BASE}.h && cmp -s ${BASE}.h.$$ ${BASE}.h ; then
     rm -f ${BASE}.h.$$
 else
     mv -f ${BASE}.h.$$ ${BASE}.h
-    chmod a-w ${BASE}.h
+    chmod -w ${BASE}.h
 fi
 $AWK -f "${DIR}/et_c.awk" "outfile=${BASE}.c.$$" "outfn=${BASE}.c" "$ROOT.et"
 if test -f ${BASE}.c && cmp -s ${BASE}.c.$$ ${BASE}.c ; then
     rm -f ${BASE}.c.$$
 else
     mv -f ${BASE}.c.$$ ${BASE}.c
-    chmod a-w ${BASE}.c
+    chmod -w ${BASE}.c
 fi
diff --git a/lib/ss/mk_cmds.sh.in b/lib/ss/mk_cmds.sh.in
--- a/lib/ss/mk_cmds.sh.in
+++ b/lib/ss/mk_cmds.sh.in
@@ -2,9 +2,11 @@
 #
 #
 
-DIR=@datadir@/ss
+datarootdir=@datarootdir@
+DIR="${DIR-@datadir@/ss}"
+SS_DIR="@SS_DIR@"
 AWK=@AWK@
-SED=sed
+SED=@SED@
 
 for as_var in \
   LANG LANGUAGE LC_ADDRESS LC_ALL LC_COLLATE LC_CTYPE LC_IDENTIFICATION \
@@ -28,8 +30,12 @@ if test -n "$_SS_DIR_OVERRIDE" ; then
 fi
 
 if test ! -f $DIR/ct_c.sed || test ! -f $DIR/ct_c.awk ; then
-    echo "mk_cmds: Couldn't find mk_cmds's template files."
-    exit 1
+    DIR="$SS_DIR"
+#    echo "Falling back to $DIR..."
+    if test ! -f "$DIR/ct_c.sed" || test ! -f "$DIR/ct_c.awk" ; then
+	echo "mk_cmds: Couldn't find mk_cmds's template files."
+	exit 1
+    fi
 fi
 
 FILE="$1"
@@ -51,6 +57,6 @@ if grep "^#__ERROR_IN_FILE" "${TMP}" > /dev/null; then
 else
 	rm -f "${BASE}.c"
 	mv -f "${TMP}" "${BASE}.c"
-	chmod a-w "${BASE}.c"
+	chmod -w "${BASE}.c"
 	exit 0
 fi
